### ISSUE TITLE
GeneralizedTime

### ISSUE THREAD

**Issue by josky88** [ezv-eets/EETS-Test-Container#1]
We expect dates in GeneralizedTime format to have the final 'Z' (as the standard for UTC).
See the "Period" and "apduDate" tags in the attached file.

Should we assume they are in UTC even without a final 'Z'?

[2020030414593555623.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4292602/2020030414593555623.zip)

**Comment by needToRoll** [comment]
As stated in the [EETS-Provider-Interface specification Section 2.1.4](https://www.ezv.admin.ch/dam/ezv/en/dokumente/abgaben/AVEA/AVAF/EETS/supplement3_eets-provider-interface.pdf.download.pdf/Supplement3_EETS-Provider-Interface.pdf):

All time data elements without a time base defined shall be in coordinated universal time (UTC).
