### ISSUE TITLE
Error on startup with last version

### ISSUE THREAD

**Issue by bdejavel** [ezv-eets/EETS-Test-Container#11]
Hello,
I have updated the component with the last version and there is an error when I try to launch it.
I have tried on Linux and Windows containers.
You will find the logs attached.

Best regards
Bernard
[ErrorLogDocker 200604.txt](https://github.com/ezv-eets/EETS-Test-Container/files/4730191/ErrorLogDocker.200604.txt)

**Comment by needToRoll** [comment]
Hello Bernard

I apologize for my late response.
It looks like you have some old version of our database shema in your docker volume.
Can you please try running:
`docker-compose rm -v ` and then try to restart the containers?

This will force all the containers to be recreated on empty volumes.

I hope this helps!

Best regards
Florian

**Comment by bdejavel** [comment]
Hello Florian,
I have tried your command and restarting containers (compose down and compose up) with this morning version and still the same error message.


Two Warn :
`WARN [eets-provider-interface-service,] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing column [country_code] in table [message]

WARN [eets-provider-interface-service,] z.r.AsyncReporter$BoundedAsyncReporter - Timed out waiting for in-flight spans to send`

And an the error :
`ERROR [eets-provider-interface-service,] o.s.boot.SpringApplication - Application run failed

eets-provider-interface-service | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing column [country_code] in table [message]`

Best regards
Bernard

**Comment by bdejavel** [comment]
I've tried "Troubleshoot/Clean / Purge data" and "Troubleshoot/Reset to factory defaults" in the Docker menus and the problem is still here.

**Comment by needToRoll** [comment]
Hi 

It appears like there is an issue on our side. We are currently working on a fix.
We will keep you posted

**Comment by needToRoll** [comment]
The latest version contains a fix. Please let us know if it works for you.
Thank you for reporting and your patience.

**Comment by bdejavel** [comment]
It works !
No errors in the logs and the container is green on Docker desktop
Thanks
Bernard

**Comment by needToRoll** [comment]
I'm glad we were able to help.
I wish you a nice day and successful tests.
