### ISSUE TITLE
Error on sending TollDeclarationADU in SST-01a

### ISSUE THREAD

**Issue by bdejavel** [ezv-eets/EETS-Test-Container#13]
Hello,
I have an issue while sending a TollDeclarationADU.
The answer is always the same : D0151E: XML tag name does not match PDU name: measuredPosition

[SHA256SignedTollDeclaration.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4838305/SHA256SignedTollDeclaration.zip)

**Comment by needToRoll** [comment]
Hello 
Could you please attach the full testcontainer log to this issue? 
This would make it easier for us to investigate it.

**Comment by bdejavel** [comment]
Hello,
Attached the eets-test-support-service Logs
[eets-provider-interface-service Logs.txt](https://github.com/ezv-eets/EETS-Test-Container/files/4847411/eets-provider-interface-service.Logs.txt)

**Comment by bdejavel** [comment]
Hello Florian,
I found the solution.
There is an error in the Supplement3 : the XML tag <MeasuredRawData> has been forgotten.

The structure of <listOfRawUsageData> must be :
<listOfRawUsageData>
	<rawDataList>
		<MeasuredRawData>
			<measuredPosition>
				<longitude>7604560</longitude>
				<latitude>47593400</latitude>
			</measuredPosition>
			<timeWhenMeasured>20200328105007Z</timeWhenMeasured>
		</MeasuredRawData>
	</rawDataList>
	<vehicleDescription>xxx</vehicleDescription>
</listOfRawUsageData>

Best regards
Bernard
