### ISSUE TITLE
SST-04b - Exceptionlist reject but http 200

### ISSUE THREAD

**Issue by bdejavel** [ezv-eets/EETS-Test-Container#14]
Hello,
We have a problem while trying to send an Exceptionlist for the SST-04b test case.
The sending of the XML goes well, with a response "1" and an http 200.
However, no Ackadu is available in the messages list and the assert verification returns an error:

```
{
    "testResultId": "SST-04b",
    "executionTime": "2020-07-03T14:31:19.840158Z",
    "state": "FAILED",
    "errors": [
        "Listener threw exception"
    ]
}
```

In the logs appears an error on parsing a date contained in the `<entryValidityStart>` XML tag
`java.time.format.DateTimeParseException: Text '2020-07-03T00:00:00.000Z' could not be parsed at index 23`

I've attached the following files :
- XML
- The assert response
- log files

[SST-04b.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4870484/SST-04b.zip)

**Comment by needToRoll** [comment]
Hello 

Sorry for the delay in my response. We have experienced some issues in the deployment to this repository.
Could you please try it again? We have implemented a fix for timezone related issues.

Please let me know if the test is now successful or not.

**Comment by bdejavel** [comment]
Hello,
With the latest version, we have an error on startup and an orange icon on Docker Desktop.
You will find the log attached.
[ErrorLogDocker OnStartup 200717.txt](https://github.com/ezv-eets/EETS-Test-Container/files/4938429/ErrorLogDocker.OnStartup.200717.txt)


Bernard

**Comment by needToRoll** [comment]
Hi 

I am terribly sorry!
 There was a conflict between two of our newest changes.
Please try again.

**Comment by needToRoll** [comment]
Hello Bernard

I would like to let you knwo that in the latest version of the test-container the commonName format has changed.
Therefore you will have to update your provider.properties file.
The value of the commonName property in there has to match the commonName of your certificate.

If you run into any other problems, please let me know.

**Comment by bdejavel** [comment]
Hello Florian,
The latest version install correctly (with the change of commonName value) and the Exceptionlist is accepted.
However, I think there is a switch between SST-04b and SST-04c.
When I run SST-04b I have an error about no entry older than 30 days, but in Supplement6 PDF the SST-04b must be “Valid list entries”. The entries older than 30 days are in the SST-04c.

```
{
    "testResultId": "SST-04b",
    "executionTime": "2020-07-21T10:35:34.813799+02:00",
    "state": "FAILED",
    "errors": [
        "Exception List does not have at least one entry with entryValidityStart older than 30 days"
    ]
}
```

Bernard

**Comment by needToRoll** [comment]
Hello Bernard

I will take a look and get backt to you asap.
If this is indeed an issue on our side I aim to publish a a fix earlier this afternoon.

Florian

**Comment by needToRoll** [comment]
Hello Bernard 
My apologies for the inconvenience  our issues have caused these past days. 
I can confirm that this is an issue on our side.The fix has been implemented an is under internal review. 
I expect the new version to be published shortly.

**Comment by needToRoll** [comment]
Hello Bernard
The fix has been published. 

Please let me know if you face any other issues.

**Comment by bdejavel** [comment]
Hello Florian,
It's OK for SST-04b.
"state": "PASSED"

I will open another ticket if I encounter other issues

Thanks
Bernard
