### ISSUE TITLE
Bean of type couldn't be found

### ISSUE THREAD

**Issue by z-abas** [ezv-eets/EETS-Test-Container#18]
Description:
Parameter 2 of constructor in ch.admin.ezv.eets.providerinterface.web.controller.ConversationsResource required a bean of type 'ch.admin.ezv.eets.security.UserContext' that could not be found.
Action:
Consider defining a bean of type 'ch.admin.ezv.eets.security.UserContext' in your configuration.

**Comment by needToRoll** [comment]
Hi,
Sorry for the late response.
The issue has been fixed in the latest commit.
We were able to adopt our CI-System to catch errors like this eralier.

Thank you for reporting this issue.
Please let me know if the startup works for you.

**Comment by needToRoll** [comment]
Issue appears to be resolved
