### ISSUE TITLE
SST-006 series doesn't work

### ISSUE THREAD

**Issue by z-abas** [ezv-eets/EETS-Test-Container#19]
Hello,

Tests sst006a through sst006 do not work.
When we execute tests for PC from SST-06a to SST-06d, PC files on FCA TC docker side are not created.

Container log provided in the attachment
[docker_exception.txt](https://github.com/ezv-eets/EETS-Test-Container/files/5318685/docker_exception.txt)

**Comment by needToRoll** [comment]
Hi z-abas,

I am having trouble reproducing your issue.
Could you please provide us with the following additional info:

- The requests that lead to the exception
- The version of the Testcontainer you are using

Kind regards
