### ISSUE TITLE
Assessment escaping

### ISSUE THREAD

**Issue by josky88** [ezv-eets/EETS-Test-Container#2]
The assessment XML document appears to have received a double escaping step (see attached file).

Should we consider this double passage as the correct behavior?

[2020030414593555623.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4292657/2020030414593555623.zip)

**Comment by needToRoll** [comment]
As described in the official [EETS-Provider-Interface specification (Section 2.5.4)](https://www.ezv.admin.ch/dam/ezv/en/dokumente/abgaben/AVEA/AVAF/EETS/supplement3_eets-provider-interface.pdf.download.pdf/Supplement3_EETS-Provider-Interface.pdf) the content of the textDetail hast to be encoded. 
The current behaviour is therefore correct.

**Comment by needToRoll** [comment]
Reopening for fourther investigation, see  previous comment

**Comment by needToRoll** [comment]
This is fixed in the newest version
