### ISSUE TITLE
Assessment tag

### ISSUE THREAD

**Issue by josky88** [ezv-eets/EETS-Test-Container#3]
In the assessment XML document (see attached file), the elements "tripStart" and "tripEnd" are missing, which however are mandatory according to the official file (journeyAssessment.xsd).

[2020030414593555623.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4292692/2020030414593555623.zip)

**Comment by josky88** [comment]
Other remarks:
- the content of element 'eetsContract' is not complete. Element 'userContract' is expected.
- the value '0' of element 'euroClass' is not valid.
- element 'relatedAssessments' is expected (in case without 'assessment' elements).

**Comment by Baraun** [comment]
@josky88: Thank your for your input and sorry for the long delay. I will work on all issues and soon we will publish an new version of the software. I will inform you asap.

**Comment by Baraun** [comment]
@josky88: we fixed several issues (#3, #4, #5). Can you give me a feedback if its works as expected?

**Comment by josky88** [comment]
Hello @Baraun 
with the last release (Provider-Interface-Service: 1.0.0-59; Test-Support-Service: 0.20.0-158) this issue seems fixed.
However, we still notice an incorrect formatting (see tag legalRemedyInstruction in attached file).
Could you verify? Thank you so much.

[2020040708430352545.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4452299/2020040708430352545.zip)

**Comment by Baraun** [comment]
@josky88 what do you mean with incorrect formatting? I see there were some whitespace characters in the german text of the legalRemedyInstruction that are deleted now. Is the document well formated now?

**Comment by josky88** [comment]
In the english text of legalRemedyInstruction there are angle bracket used, I suppose, as angle quotes, but they are inserted asymmetrically (the left ones as `&amp;lt;&amp;lt;` and the right ones as `&gt;&gt;` - see attached file). It would be preferable not to have angle quotes, but if necessary, they should be in the first format, it is correct?
Thanks
[legalRemedyInstruction.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4455557/legalRemedyInstruction.zip)

**Comment by Baraun** [comment]
@josky88 We removed the << and now there should be the real english translation
