### ISSUE TITLE
Test Assert always FAILED

### ISSUE THREAD

**Issue by josky88** [ezv-eets/EETS-Test-Container#4]
Whenever we execute tests sst-05a and sst-06a, we receive (from assert) the following 
`{"errors" : ["State of outgoing message is not PUBLISHED." ], "executionTime": (...), "state": "FAILED", "testResultId": "SST-(...)"}` 
as testResult, instead of PASSED as we expect.

Attached below the logs and the files exchanged in the two tests.
[SST-05a.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4343111/SST-05a.zip)
[SST-06a.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4343112/SST-06a.zip)

**Comment by josky88** [comment]
In the last release (Provider-Interface-Service: 1.0.0-59; Test-Support-Service: 0.20.0-158) this problem continues to occur (and also for tests sst-01a and sst-02a).
Please verify. Thanks for support

**Comment by Baraun** [comment]
@josky88 i tried the test SST-05a and it worked. Your logs that came from the provider-interface-service look good. 

Can you please send me the docker logs from the test-support-service? You can get the logs by the command
`docker logs eets-testcontainer-testsupportservice`

**Comment by josky88** [comment]
@Baraun in the attached zip you'll find both logs (testsupport and providerinterface) for test sst-05a.
I look forward to your feedback, thank you.
[sst-05a.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4456961/sst-05a.zip)

**Comment by Baraun** [comment]
@josky88 it fought today with similar problems when testing your issues. Could you backup your certificates and then call (safety first...)
`docker-compose build --no-cache --pull` in the root directory? I think the old version of the containers get cached. 

You can ensure yourself, when checking the log file from provider interface service. When you start the test sst-05a should see the new legal remedies:
`eets-provider-interface-service                  | English is not an official language of the Swiss Confederation. This translation is provided for information purposes only and has no legal force.
eets-provider-interface-service                  | An objection against this assessment ruling can be filed within 30 days. The objection is a prerequisite for a subsequent administrative appeal procedure.
eets-provider-interface-service                  | The objection must be submitted in writing to the Directorate General of Customs, Division traffic charges, Monbijoustrasse 91, 3003 Bern. It must contain the request, the grounds supporting it, state the evidence and be signed by the objecting party or his/her representative. The evidence must be enclosed.
eets-provider-interface-service                  | The time limit does not include the following periods (Art. 22a of the APA; SR 172.021):
eets-provider-interface-service                  | a)    from the seventh day before Easter up to and including the seventh day after Easter;
eets-provider-interface-service                  | b)    from 15 July up to and including 15 August;
eets-provider-interface-service                  | c)    from 18 December up to and including 2 January.`

In your logs, you see still the old one:
`Instructions on legal remedies
English is not an official language of the Swiss Confederation. This translation is provided for information purposes only and has no legal force.
&amp;lt;&amp;lt;Gegen diese Veranlagungsverfügung kann innerhalb von 30 Tagen Einsprache erhoben werden. Die Einsprache ist Voraussetzung für ein anschliessendes Verwaltungsbeschwerdeverfahren.
Die Einsprache ist schriftlich an die Oberzolldirektion, Abteilung Verkehrsabgaben, Monbijoustrasse 91, 3003 Bern zu richten. Sie hat die Begehren, deren Begründung mit Angabe der Beweismittel und die Unterschrift des Einsprechenden oder seines Vertreters zu enthalten. Die Beweismittel sind beizulegen.
Die Frist steht still (Art. 22a VwVG; SR 172.021):
a)    vom siebten Tag vor Ostern bis und mit dem siebten Tag nach Ostern;
b)    vom 15. Juli bis und mit 15. August;
c)     vom 18. Dezember bis und mit dem 2. Januar.&gt;&gt;&lt;/legalRemedyInstruction`

**Comment by josky88** [comment]
Hello @Baraun,
in the last release, this problem continues to occur (as you can see in the last sections of attached log files).
Thanks for support
[log.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4462250/log.zip)

**Comment by Baraun** [comment]
@josky88 i think we are close to a solution... Now its an subsequent error of my test data corrections in #5. Can you please get the newest versions and rebuild the docker images by 
`docker-compose build --no-cache --pull`

**Comment by josky88** [comment]
Hello @Baraun,
in the last release, this problem continues to occur (see attached log files).
Are we doing something wrong in the procedure?
The problem #5 seems to have been solved, thanks.
[log.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4475172/log.zip)

**Comment by Baraun** [comment]
@josky88 after a long time searching (because the logs are looking good so far) i'm pretty sure whats happening... 

1. You start the test sst-05a
2. A BillingDetailsADU is published
3. You call getMessages and receive a list of unconfirmed messages (1 unconfirmed in this case)
4. You get the Detail of a message with the Apdu Identifier for the acknowledge
5. You confirm the message by deleting the message
6. You acknowledge the message
7. You verify the test (it fails)

The problem is (it not your fault, i have to discuss this internally) for this test (and probably for all others) you just have to get the details of a message but NOT confirm them. Internally there's a state change and in verifyTest the state of the message is validated. It must be PUBLISHED and not CONFIRMED. Can you adapt for the tests or do we have to change because you cannot change your system?

**Comment by Baraun** [comment]
@josky88 we discussed it internally and we will do a correction in the test container. The tests should not fail when the messages are confirmed. This correction should be made today. So you can wait without made any adaptions to your system.

**Comment by josky88** [comment]
Hello @Baraun,
thanks for the correct reconstruction of our flow and for the willingness to change your test system.
Alternatively, we should have changed our main system, so I think the proposed solution is the most correct.
Thanks again for the support, I await the next release

**Comment by needToRoll** [comment]
Hello @josky88 

The version containing the fix is now publicly available. 
We look forward to your feedback.

**Comment by Baraun** [comment]
@josky88 should be implmented. Good luck :-)

**Comment by josky88** [comment]
Hello @needToRoll 
with the latest release this problem has been solved, thanks for the support.
However, we noticed another problem and opened the issue #9
