### ISSUE TITLE
Missing input data in sst-05c and sst-05d

### ISSUE THREAD

**Issue by josky88** [ezv-eets/EETS-Test-Container#5]
When executing tests sst-05c and sst-05d, the xml files we receive do not contain the _relatedBillingDetails_ field, as required by the Test Specification.

Attached below, the files received and the logs of the containers.
[SST-05c.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4343191/SST-05c.zip)
[SST-05d.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4343220/SST-05d.zip)

**Comment by josky88** [comment]
In the last release (Provider-Interface-Service: 1.0.0-59; Test-Support-Service: 0.20.0-158) the _relatedBillingDetails_ field is now present but contains the same value as the billingDetailsId (see attached files)! Please verify. Thanks for support

[sst-05c.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4455712/sst-05c.zip)

**Comment by Baraun** [comment]
@josky88: this is a test data problem. I fixed it to the following solution for test SST-05c and SST-05d:
the billingDetailsId ist newly: BillingDetailsId-2 (see Chapter 6.1 Overview - Test data matrix)
the relatedBillingDetailsId is newly: BillingDetailsId-1

**Comment by josky88** [comment]
Hello @Baraun,
in the last release, preparing tests sst-05c and sst-05d does not lead to the publication of any message.
In the attached log files you will see there's some parsing error.
[log.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4462225/log.zip)
