### ISSUE TITLE
Provider not authenticated

### ISSUE THREAD

**Issue by bdejavel** [ezv-eets/EETS-Test-Container#6]
I have an issue with tls authentication.
I tested API with postman and the answer is always "Provider not authenticated.  id: 49, countryCode: FR

I applied the different prerequisites:
- create selfSigned root certificate and http client certificate with xca
- Install docker for Windows
- save the root certificate to "cert/client_ca.crt"
- modify provider.properties
- launch command "docker-compose up -d"
- the test URL is : https://localhost:443/api/messages/fromFCA/FR/49/

Did I missed something?

Attached below, the logs of the containers.
[DockerLog.txt](https://github.com/ezv-eets/EETS-Test-Container/files/4360157/DockerLog.txt)

**Comment by needToRoll** [comment]
Could you please try to set the cn in your provider properties file to:
CN=Axxes,OU=Axxes,O=Axxes,C=FR

And try again?

**Comment by bdejavel** [comment]
Hello,
I works, I have a HTTP 200 with a "[]" in the body.
Thanks a lot.
Have a good day and take care.

Bernard
