### ISSUE TITLE
Incorrect data encoding

### ISSUE THREAD

**Issue by josky88** [ezv-eets/EETS-Test-Container#7]
In the attached BillingDetails, received performing test sst-05b with default test data, the following attribute are incorrect:
- userId.obeId.equipmentOBUId 0000102030'H -> according to EN ISO 14906, the leading byte must always be 04 (we expect 0400102030'H).
- userId.licensePlateNumber.licensePlateNumber 48484142313233'H -> according to Supplement2 a LPN shorter than 10 characters must be padded with NULL characters (00) so as to achieve a total of 10 characters (we expect 48484142313233000000'H).

With regard to the second point, the length determinant also seems necessary according to Supplement2, could you confirm it? So, in that case, we expect 0A48484142313233000000'H.

[2020030413231709133.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4394612/2020030413231709133.zip)

**Comment by josky88** [comment]
We also noticed that, in the default test data, the UserId-3 does not contain the AN2015 plate but the HIH123 plate (that of the UserId-2), contrary to what reported in Supplement6.

**Comment by needToRoll** [comment]
Hello @josky88 
Thank you for reporting your issues.

Regarding your first point, I am sorry that our default dataset is inacurrate, however you should be able to overwrite it. See Supplement6 section 6.6
The formatting of the LPN is a bug on our side and we are currently working on a fix. 
The fix should be available for you tomorrow.

**Comment by josky88** [comment]
Hello @needToRoll 
In the last release (Provider-Interface-Service: 1.0.0-59; Test-Support-Service: 0.20.0-158), we receive license plates of correct length (min 10) but still without plate length in the initial character (e.g. `<licencePlateNumber>35373331333033323330</licencePlateNumber>` instead of `<licencePlateNumber>0A35373331333033323330</licencePlateNumber>`, see attached file).
Can you kindly specify if it is a bug or is it the correct behavior (and so in the TollDeclarations you expect the same format without initial character)?
Thank you so much.

[2020040708430352545.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4452210/2020040708430352545.zip)

**Comment by Baraun** [comment]
@josky88 this is the correct behaviour. Theres no length indicator that should be prefixed, only the plain licence plate number (padded of course) should be transmitted.

**Comment by josky88** [comment]
Perfect, also in the tollDeclaration we will not send the total length of the plate as the first character.
Thanks
