### ISSUE TITLE
Cannot run eets-provider-interface-service

### ISSUE THREAD

**Issue by z-abas** [ezv-eets/EETS-Test-Container#8]
Hi, have a problem in running eets-provider-interface-service though docker.
Exception stack trace is attached.
Am i missing something here?

Thanks!
[eets-provider-interface-service log.txt](https://github.com/ezv-eets/EETS-Test-Container/files/4432722/eets-provider-interface-service.log.txt)

**Comment by Baraun** [comment]
@z-abas: can you please try again? We fixed the configuration problem.

**Comment by z-abas** [comment]
Hello,

Everything is ok now.
Thank you!

ŽAbas
