### ISSUE TITLE
Wrong IssueCode in sst-06c

### ISSUE THREAD

**Issue by josky88** [ezv-eets/EETS-Test-Container#9]
By running the sst-06c test, this fails because the Ack IssueCode is not 11002 (see attached log files).
But the IssueCode for the paC-unknownBillingDetails is NOT 11002 (as also incorrectly reported in Supplement6) but 11102 (as can be verified in Supplement3).
Thanks for fixing it.
[log.zip](https://github.com/ezv-eets/EETS-Test-Container/files/4480676/log.zip)

**Comment by needToRoll** [comment]
Hello @josky88 
Thanks again for reporting and for your patience.
We just publised a fix.  However it might be a few days until we are able  to update the sepecifications due to holiday absences.

**Comment by josky88** [comment]
Hello @needToRoll 
with the latest release this problem has been solved, thanks for the support.
No problem for us on the days needed for the specifications update.
Best regards
